[package]
name = "il_cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
il_core.workspace = true
il_data.workspace = true
il_sim_battle.workspace = true
clap.workspace = true
anyhow.workspace = true
json5.workspace = true
serde.workspace = true

[lints]
workspace = true
