[package]
name = "il_sim_battle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Iron Legion headless battle simulation."

[dependencies]
il_core.workspace = true
il_data.workspace = true
bevy_ecs.workspace = true
bevy_tasks.workspace = true
serde.workspace = true
serde_json.workspace = true
postcard.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
json5.workspace = true

[lints]
workspace = true
